### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by sukumar1612**
1. Refactoring code and project structure
2. Formatting code using Black and Isort
3. Removing unused code
4. Using Pydantic models to pass data
5. Using Type hints

### CODE REVIEW

**Comment by mathanamathav** [comment]
@sukumar1612 there is a significant improvement in the boot-up of website!

**Comment by mathanamathav** [comment]
@Hafiz408 this is a big change in the code-base it's completely refactored , cleaned up version let's check the website if it works fine for all test cases ?

**Comment by Hafiz408** [comment]
> 

Sure, I will look into it.

**Comment by mathanamathav** [comment]
we will wait until the college opens the attendance portal , test it and merge it. for now we will work on CGPA code,

**Comment by mathanamathav** [comment]
fixed all the issues and now shifted the code base! @sukumar1612 @Hafiz408

**Review by mathanamathav — APPROVED** [review]

**Pull request merged**
