### PR TITLE
Functionality added to display CGPA details

### PR DESCRIPTION
**Pull request by Hafiz408**
## Motivation & Description:

To calculate and display CGPA up to the previous semester.

Screenshot_20230107_115352

### CODE REVIEW

**Comment by mathanamathav** [comment]
@Hafiz408 round up the CGPA to 2 or 3 decimal places.

**Comment by mathanamathav** [comment]
Nice work @Hafiz408 
fyi @Partha16 @jegadeesh2001 u guys update if you any feedback !!

**Comment by Hafiz408** [comment]
@mathanamathav  Any particular font or colour idea already under use that I could reuse?

**Comment by mathanamathav** [comment]
> @mathanamathav Any particular font or colour idea already under use that I could reuse?

we are currently using google's font - Alfa Slab One https://fonts.google.com/specimen/Alfa+Slab+One?query=alf 
size same as the course code with box or two liness

**Comment by mathanamathav** [comment]
LGTM i am merging it with main branch @Hafiz408 .

**Pull request merged**
