### PR TITLE
Bunker functionality algorithm updation

### PR DESCRIPTION
**Pull request by Hafiz408**
## Description:

- [x]  Algorithm modified
- [x]  Display exemption info in UI
- [x]  Modify & beautify UI for mobile
- [x]  Indicate a warning or tip saying its best to have physical attendance above 75

color palette used in this UI -> https://colorhunt.co/palette/222831393e4600adb5eeeeee

### CODE REVIEW

**Comment by mathanamathav** [comment]
@Partha16 we have to check the algo working properly which we discussed for that corner case.

**Comment by mathanamathav** [comment]
@Hafiz408 @jegadeesh2001 @jegadeesh2001 major UI update done how is the changes ?

**Comment by Hafiz408** [comment]
> @Hafiz408 @jegadeesh2001 @jegadeesh2001 major UI update done how is the changes ?

Screenshot 2023-01-15 175541
 Lets increase the font size and change the font style for the note below roll no as its not clearly visible. 
Also, the remark column doesn't fit in a single line so lets change **take leave** to **bunk** and reduce **with exemption** columns size.
Otherwise, the new design looks great.

**Comment by mathanamathav** [comment]
> > @Hafiz408 @jegadeesh2001 @jegadeesh2001 major UI update done how is the changes ?
> 
> Screenshot 2023-01-15 175541 Lets increase the font size and change the font style for the note below roll no as its not clearly visible. Also, the remark column doesn't fit in a single line so lets change **take leave** to **bunk** and reduce **with exemption** columns size. Otherwise, the new design looks great.

Done @Hafiz408 👍🏻

**Comment by mathanamathav** [comment]
Screenshot_20230115_075047

@Hafiz408 ?

**Comment by Hafiz408** [comment]
> Screenshot_20230115_075047
> 
> @Hafiz408 ?

LGTM

**Comment by mathanamathav** [comment]
>

**Review by mathanamathav — APPROVED** [review]

**Pull request merged**
